config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    resources :posts, only: %i[edit update destroy create] do
      resources :comments, only: %i[edit update destroy create]
      resources :likes, only: %i[create destroy]
    end
  end

  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  authenticated :user do
    root to: 'user/posts#index', as: :user_root
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to new_user_session_path, notice: "Login to continue"
    end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserController
  before_action :set_post, only: %i[create]
  before_action :set_comment, except: %i[create]

  def create
    if params[:comment][:parent_id].present?
      parent_comment = Comment.find(params[:comment][:parent_id])
      @comment = parent_comment.replies.build(comment_params)
      @comment.post = parent_comment.post
    else
      @comment = @post.comments.build(comment_params)
    end
    @comment.user = current_user
    if @comment.save
      redirect_to user_root_path, notice: 'Commented!!'
    else
      redirect_to user_root_path, alert: @comment.errors.full_messages.to_sentence
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to user_root_path, notice: 'Comment Updated!!'
    else
      redirect_to user_root_path, notice: @comment.errors.full_messages.to_sentence
    end
  end

  def destroy
    if @comment.destroy
      redirect_to user_root_path, notice: 'Comment Deleted Successfully'
    else
      redirect_to user_root_path, notice: 'Something went wrong'
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < UserController
  before_action :set_like, except: %i[create]

  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    if @like.save
      redirect_to user_root_path, notice: 'Post Liked'
    else
      redirect_to user_root_path, alert: 'Like could not be created'
    end
  rescue ActiveRecord::RecordNotUnique
    @like = Like.find_by!(user: current_user, post_id: params[:post_id])
    @like.destroy
    redirect_to user_root_path, notice: 'Like removed'
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:post_id])
    if @like&.destroy
      redirect_to user_root_path, notice: 'Like removed'
    else
      redirect_to user_root_path, alert: 'Like could not be removed'
    end
  end

  private

  def set_like
    @like = Like.find(params[:id])
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
  before_action :set_post, except: %i[index create]

  def index
    @posts = Post.all
    @new_post = Post.new
    @comments = Comment.where(post_id: @posts.map(&:id)).index_by(&:post_id)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_root_path, notice: 'Post successfully created'
    else
      redirect_to user_root_path, alert: @post.errors.full_messages.to_sentence
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to edit_user_post_path(@post), notice: 'Post updated Successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      redirect_to user_root_path, notice: 'Post Deleted Successfully'
    else
      redirect_to user_root_path, notice: 'Something went wrong'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    layout 'user'
    before_action :authenticate_user!

    def index
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>
    The Home Page
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
        <ul>
            <li>
                Your Profile
            </li>
            <li>
                Find People
            </li>
            <li>
                Friend List
            </li>
            <li>
                Messages
            </li>
        <ul>
    <div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if form.object.errors.any? %>
  <div>
  <% form.object.errors.full_messages.each do |message| %>
      <div>
          <%= message %>
      </div>
  <% end %>
  </div>
<% end %>

app/views/user/comments/_form.html.erb
<%= form_with model: [:user, comment.post, comment] do |form| %>
  <%= render "shared/error", form: form %>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <%= form.button %>
<% end %>

app/views/user/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", comment: @comment %>

app/views/user/index.html.erb
<h1>User Feed</h1>

app/views/user/posts/_comment.html.erb
<p class="<%= comment.parent_id.present? ? 'nested-comment' : '' %>">
  <%= comment.user.email %>: <%= comment.body %>
</p>
<% if comment.user == current_user %>
  <div>
    <%= link_to 'Edit Comment', edit_user_post_comment_path(comment.post, comment)  %>
    <%= button_to 'Delete Comment', [:user, comment.post, comment], method: :delete, data: {turbo_confirm: "Are you sure ?"} %>
  </div>
<% end %>
<div class="<%= comment.parent_id.present? ? 'nested-comment-form' : '' %>">
  <%= render "commentform", post: comment.post, comment: Comment.new(parent_id: comment.id), label: "Reply to this comment" %>
</div>

app/views/user/posts/_commentform.html.erb
<%= form_with model: [:user, post, comment] do |form| %>
  <%= render "shared/error", form: form %>
  <%= form.hidden_field :parent_id, value: comment.parent_id %>
  <div>
    <%= form.label :body, label %>
    <%= form.text_field :body %>
  </div>
  <%= form.button %>
<% end %>

app/views/user/posts/_form.html.erb
<%= form_with model: [:user, post] do |form| %>
    <%= render "shared/error", form: form %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>
    <%= form.button %>
<% end %>

app/views/user/posts/_like.html.erb
<% if current_user && current_user.likes.exists?(post_id: post.id) %>
  <%= button_to 'Unlike', user_post_like_path(post, id: current_user.likes.find_by(post_id: post.id).id), method: :delete, data: { turbo_confirm: "Are you sure you want to unlike this post?" } %>
<% else %>
  <%= button_to 'Like', user_post_likes_path(post), method: :post %>
<% end %>

app/views/user/posts/_post.html.erb
<div>
  <strong>
    <%= post.title %>
  </strong>
  <p>
    <%= post.body %>
  </p>
  <div>
    <span>
      <%= render 'like', post: post %>
    </span>
  </div>
  <% if current_user == post.user %>
    <div>
      <%= link_to 'Edit Post', edit_user_post_path(post) %>
      <%= button_to 'Delete Post', [:user, post], method: :delete, data: { turbo_confirm: "Are you sure ?" }  %>
    <div>
  <% end %>
  <div>---------</div>
  <%= render "commentform", post: post, comment: Comment.new(parent_id: nil), label: "Your Comment" %>
  <% unless post.comments.count.zero? %>
    <div>Comments</div>
  <% end %>
  <% post.comments.each do |comment| %>
    <%= render "comment", comment: comment %>
  <% end %>
</div>

app/views/user/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/user/posts/index.html.erb
<h1>
    Posts
</h1>

<%= render "form", post: @new_post %>

<% @posts.each do |post| %>
    <%= render "post", post: post, comment: @comments[post.id] %>
<% end %>